### ISSUE TITLE
Failed to download course materials 

### ISSUE THREAD

**Issue by TheOkayMan** [merberich/teachable_dl#8] opened 2022-06-13 01:11 UTC
Failed to download course materials at URL: https://shift-education.teachable.com/courses/1635455/lectures/38284604. Cause: Exceeded 30 redirects.

Command run was `python teachable_dl.py -c D:\Users\wrigh\Downloads\teachable.com_cookies.txt -o d:\dwhelper -u https://shift-education.teachable.com/courses/1635455/lectures/38284604`

**Comment by merberich** [comment] 2022-06-13 01:17
Unfortunately I can't reproduce because I dont have access to that course and can't determine what resource it's trying to download. Can you paste a full traceback of the error shown when you run the command?

**Comment by TheOkayMan** [comment] 2022-06-13 01:38
`python teachable_dl.py -c D:\Users\wrigh\Downloads\teachable.com_cookies.txt -o d:\dwhelper -u https://shift-education.teachable.com/courses/1635455/lectures/38284604`
```
Fetching course url: 'https://shift-education.teachable.com/courses/1635455/lectures/38284604'
Failed to download course materials at URL: https://shift-education.teachable.com/courses/1635455/lectures/38284604. Cause: Exceeded 30 redirects.
```

Is this what you are after, I am not that familiar with python and doing traceback

**Comment by merberich** [comment] 2022-06-13 04:26
Sorry, I had forgotten I wrapped the exceptions up.

Also I just noticed the link you ran with is to a specific lecture. My tool will only accept the course URL from its home page - in your case, I think it would be `https://shift-education.teachable.com/courses/enrolled/1635455/`.

Try that URL (or the correct top-level URL, since I can't access the course myself) and see if it resolves your problem.

If that doesn't work, I'd request that you:
(1) retry with the verbose option (`-v`) so I can see specifically where it's failing, and 
(2) verify that this isn't a problem with their web site by opening the lecture URL in a browser

**Comment by TheOkayMan** [comment] 2022-06-13 04:33
I can't get -v to work

This is all I get

```
PS D:\dwhelper> python teachable_dl.py -v -c D:\Users\wrigh\Downloads\teachable.com_cookies.txt -o d:\dwhelper -u https://shift-education.teachable.com/courses/enrolled/1584353
Fetching course url: 'https://shift-education.teachable.com/courses/enrolled/1584353'
Failed to download course materials at URL: https://shift-education.teachable.com/courses/enrolled/1584353. Cause: Exceeded 30 redirects.
PS D:\dwhelper> python teachable_dl.py -v
usage: teachable_dl.py [-h] -c COOKIES [-u URL [URL ...]] [-o OUTPUT] [-v]
teachable_dl.py: error: the following arguments are required: -c/--cookies
PS D:\dwhelper> python teachable_dl.py -c D:\Users\wrigh\Downloads\teachable.com_cookies.txt -o d:\dwhelper -u https://shift-education.teachable.com/courses/enrolled/1635455 -v
Fetching course url: 'https://shift-education.teachable.com/courses/enrolled/1635455'
Failed to download course materials at URL: https://shift-education.teachable.com/courses/enrolled/1635455. Cause: Exceeded 30 redirects.
PS D:\dwhelper> python teachable_dl.py -c D:\Users\wrigh\Downloads\teachable.com_cookies.txt -u https://shift-education.teachable.com/courses/enrolled/1635455 -v
Fetching course url: 'https://shift-education.teachable.com/courses/enrolled/1635455'
Failed to download course materials at URL: https://shift-education.teachable.com/courses/enrolled/1635455. Cause: Exceeded 30 redirects.
PS D:\dwhelper>
```
________________________________

**Comment by merberich** [comment] 2022-06-13 04:38
The last call looks correct, which means the script is failing to grab from the root URL. Can you confirm the course URL is correct in the browser? The only other thing I can think of is if your cookies have expired - try re-generating them.

I'll separately see if the script is failing for courses I've already downloaded too. If that's the case, this may take more time to debug.

**Comment by TheOkayMan** [comment] 2022-06-13 04:42
It works in the browser, and I have updated cookies and no luck. Thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by merberich** [comment] 2022-06-13 05:39
Okay, unfortunately, I think the method this script uses to log into Teachable as a service no longer works, they have switched to a single-sign on model and I'm not sure if cookies can be used to track the session information any longer.

It looks like I need to sunset this repository, or at least state that this won't work unless I can find an alternative login method :(

**Comment by merberich** [comment] 2022-06-13 07:05
Closed as of: https://github.com/merberich/teachable_dl/commit/7604a05f00f1a04af1f84ae15cfb897b7f016a17

**Comment by merberich** [comment] 2022-06-13 07:06
Closed as of: https://github.com/merberich/teachable_dl/commit/7604a05f00f1a04af1f84ae15cfb897b7f016a17

**Closed as not planned by merberich** 2022-06-13 07:06 UTC

**Comment by pedrosimao** [comment] 2022-11-17 11:31
Any news on that front? I am desperate to find a solution to download a paid course that will be deleted soon.

**Comment by merberich** [comment] 2022-11-19 08:29
Unfortunately we would each need our own API keys to download courses now - though it's possible to still do so manually with browser inspect tools. Best of luck.
